services:
  # --- Servicio web principal ---
  - type: web
    name: elmailer-web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://elmailer-segumin.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: SESSION_DRIVER
        value: file
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_URL
        fromService:
          name: elmailer-redis
          type: redis
          property: connectionString
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        sync: false      # se define manualmente en el panel
      - key: MAIL_PASSWORD
        sync: false      # App Password de Gmail (16 caracteres)
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "El Mailer"
      - key: APP_KEY
        sync: false      # pega aquí tu clave base64 de Laravel

  # --- Worker de colas (envía correos) ---
  - type: worker
    name: elmailer-worker
    env: docker
    plan: free
    autoDeploy: true
    dockerCommand: ["php","artisan","queue:work","--tries=3"]
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://elmailer-segumin.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: SESSION_DRIVER
        value: file
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_URL
        fromService:
          name: elmailer-redis
          type: redis
          property: connectionString
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "El Mailer"
      - key: APP_KEY
        sync: false

  # --- Redis administrado ---
  - type: redis
    name: elmailer-redis
    plan: free
    ipAllowList: []
